### ISSUE TITLE
why it is 72 * 96?

### ISSUE THREAD

**Issue by Mohan-Zhang-u** [google-research/football#125]
May I ask, why in the extracted representation, each of the layer is represented in 72 * 96 observation bytes? Is 96 the width of the football pitch and 72 the height of the football pitch?

**Comment by qstanczyk** [comment]
It was selected as a balance between training quality (step complexity) and training time (time of inference, communication load due to sending observations etc). It wasn't super-tuned, so changing the size might benefit your setup.
SEED_RL paper provides some experiments with different sizes, which show bigger map can provide better step complexity: https://arxiv.org/abs/1910.06591
