### ISSUE TITLE
Malinformed environment ID on Mac OSX

### ISSUE THREAD

**Issue by jlim13** [google-research/football#133]
![Screen Shot 2020-04-01 at 2 59 20 PM](https://user-images.githubusercontent.com/36393441/78175759-5febee00-7429-11ea-9b32-9e4bccc418ff.png)

I try to run python3 -m gfootball.examples.run_ppo2 --dump_full_episodes=True --render=True and I get this error. I also get this error when trying to play the game. All of the installations went smoothly.

**Comment by vi3itor** [comment]
Hi @jlim13! I might try to help you here. I didn't have any errors with OpenAI's gym environment, but I had an error with multiprocessing, similar to [this](https://github.com/ansible/ansible/issues/32499). And their [solution](https://github.com/ansible/ansible/issues/32499#issuecomment-341578864) worked for my Mac running Mojave, you can even set an environment variable in bash, as suggested [here](https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr). 
Before installing OpenAI's baselines, I installed openmpi as suggested on the repository [page](https://github.com/openai/baselines) with the following command: 
`brew install openmpi` 
I also had to downgrade dm-sonnet version because version 2.0 only supports TF 2.0. So you should run: 
`pip3 install "dm-sonnet<2.0.0`
Also, please make sure that you pulled the latest commit from master and that you don't have any changes with git status. Please provide the full log instead of a screenshot.

**Comment by jlim13** [comment]
Hey, for some reason I didn't have the error when I downloaded the packages + ran the script outside of the Conda environment.
