### ISSUE TITLE
icu4c installing error

### ISSUE THREAD

**Issue by LeonIdeal** [google-research/football#136]
My mac os version is macOS MOjave 10.14.6 
when I installed packages using `brew install boost-python3`
It appeared 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/19504637/78467780-c2ebc680-7742-11ea-92a5-9e7388e09f7e.png">
Have anyone met this bug?

**Comment by vi3itor** [comment]
@LeonIdeal Did you try searching for the error message? For example, [here](https://discourse.brew.sh/t/curl-35-libressl-ssl-connect-ssl-error-syscall-in-connection-to-homebrew-bintray-com-443/6581/6) or [here](https://github.com/libressl-portable/portable/issues/369) happened to be a similar problem. There might be numerous reasons, such as `curl` comes from Anaconda installation (if you have one) instead of homebrew, the other reason might be because of outdated packages in homebrew. Try searching for "brew LibreSSL  SSL_read error" and try the provided solutions.
I think this issue can be closed.

**Comment by LeonIdeal** [comment]
Thanks for replying! I closed the proxy behind the internet and it worked.
But now I met the problem 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/19504637/78473374-baab7f80-7772-11ea-8f82-56617bf0dade.png">
I searched issues, and I looked up the CMakeLists and check, then the boost part goes like 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/19504637/78473415-14ac4500-7773-11ea-8d0e-1f0ab1e9c516.png">

And I wondered if Mac OS can fit in this CMakeList?

**Comment by vi3itor** [comment]
Well, as far as I can see, you have python 3.6, but if you installed the latest version of boost (1.72.0) it uses python 3.7. 
In my opinion, you have 2 options:
1) upgrade python from 3.6 to 3.7
2) try installing a specific version of boost, that supports python 3.6 
If you choose to upgrade python, don't forget to remove football-env virtual environment and create a new one.

**Comment by vi3itor** [comment]
@LeonIdeal Have you managed to upgrade Python to version 3.7? 
If you're facing a problem with boost-python3 now, please try my solution from the other [issue](https://github.com/google-research/football/issues/128#issuecomment-613850910).

**Comment by nbro** [comment]
@vi3itor I was getting the error described in this comment https://github.com/google-research/football/issues/136#issuecomment-609401203 and I am using Python 3.7.7. I installed boost-python3 with the command `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/527d96f84d4632d30b281ef5b26717e0a75edcb4/Formula/boost-python3.rb` (which is suggested [here](https://github.com/google-research/football/issues/128#issuecomment-613850910)), and these are the dependencies I installed with `brew` (you can execute the command `brew list --versions $(brew leaves)` to get the installed packages and their versions)

```
boost-python3 1.72.0
cmake 3.17.3
ffmpeg 4.2.3_1
graphviz 2.44.0
gtk+3 3.24.18_1
imagemagick 7.0.10-17
poppler 0.89.0
py2cairo 1.18.2_1
pygobject3 3.36.1
python@2 2.7.17
sdl2_gfx 1.0.4
sdl2_image 2.0.5
sdl2_ttf 2.0.15
sshfs 2.10_2
```

In fact, I installed all the dependencies specified in the command `https://github.com/google-research/football`, except for `git`, which I already had. I also had installed `python3`, but the problem was apparently that `python3` wasn't linked, so I executed the following command:

```
brew link --overwrite python3
```

WARNING: this will unlink your python2 version (but I am not really sure of the consequences!). Anyway, after having done this, I don't get the error anymore.

**Comment by vi3itor** [comment]
@nbro Thanks for the report. 
I would add if anyone faces a similar problem, running `brew doctor` might give some hints on linking issues with `python3` installation.

**Comment by qstanczyk** [comment]
PR #277 is not merged, Windows support added to the environment. Thanks @vi3itor for your great contribution. Closing this issue.
