### ISSUE TITLE
Impala agent used in the paper experiments

### ISSUE THREAD

**Issue by kvr777** [google-research/football#16]
Hi, 
thank you for the great environment for RL experiments.
What implementation of IMPALA agent did you use in your experiments? Did you adapt this code https://github.com/deepmind/scalable_agent or write your own implementation?  Do you plan to add your implementation in this repository ?

**Comment by kkurach** [comment]
Hi Kirill,

yes, we adapted exactly the open-source code that you pointed to. We use it together with internal google cloud, and it's using many internal components (distributed storage for keeping models and replays, system for starting experiments, etc), so it rather would be hard to release it as-is, but fundamentally it's the same algorithm as scalable_agent. Because of that, I'm not even sure if releasing "our IMPALA" is a good idea as it might create more confusion.

Regarding hyper-parameters, we tuned them quite a bit - you can see our current setup in Table 2 in the paper.

**Comment by kvr777** [comment]
ok, great. Thank you

**Comment by esquires** [comment]
Hi @kkurach . Would it be possible to post how you changed ``create_environment`` for ``experiments.py`` in the impala fork? It looks like in the impala code they created a PyProcess wrapper around a DMLab (the PyProcessDmLab object) environment and then wrapped that with a FlowEnvironment. I am curious if/how you all did the same thing.
