### ISSUE TITLE
Clarity regarding the units of ball?

### ISSUE THREAD

**Issue by jlim13** [google-research/football#161]
the x and y seems to be scaled between [-1,1]. what about z? I see it can go up to 10+. Does that mean meters?

**Comment by qstanczyk** [comment]
X is in the range [-1,1], Y is in the range [-0.42, 0.42]. Z is not scaled and exposed directly from the game engine. I guess it would make sense to re-scale ranges, so that they are aligned, but that would make environment incompatible, so it would have to be v3 of the environment. Once we have more backward-incompatible changes collected we will consider cutting such a release.
