### ISSUE TITLE
No color when I run the demo

### ISSUE THREAD

**Issue by Gelisi** [google-research/football#171]
I try：MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game
But the window only has black and white——two colors? 
![image](https://user-images.githubusercontent.com/44775341/81535201-f4882b00-939b-11ea-99e6-2d09832d393e.png)

I run the project on vmware(15 pro)
![image](https://user-images.githubusercontent.com/44775341/81535147-dc181080-939b-11ea-9f1e-2f8f1dffaa72.png)

I can't remember how much time I have spent on this thing.....

**Comment by Gelisi** [comment]
But when I enter the game, it looks like this:

![image](https://user-images.githubusercontent.com/44775341/81535441-61032a00-939c-11ea-8f9b-d0bcb935d7d6.png)

**Comment by vi3itor** [comment]
@Gelisi The intro screen uses very simple shaders to draw the images on the screen, that's why they are colorful. 
The game itself requires OpenGL 3.2+ to draw the lighting effects. The most likely scenario: your virtual machine doesn't support that version of the OpenGL. Check [here](https://docs.vmware.com/en/VMware-Workstation-Pro/15.0/com.vmware.ws.using.doc/GUID-F5186526-2382-4F4A-8009-3D07773A1404.html) on setting up 3D acceleration in VMWare.
You can even search for some games that use OpenGL 3.2 and try running them in the virtual machine. 

> I can't remember how much time I have spent on this thing.....

Instead, you might consider installing Ubuntu next to Windows. There are tons of guides like [this one](https://www.tecmint.com/install-ubuntu-alongside-with-windows-dual-boot/) available. It probably won't take more than couple of hours, and you'll have a fully functional Ubuntu that gets the maximum of your hardware.
