### ISSUE TITLE
About Play vs built-in AI

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#175]
Run python3 -m gfootball.play_game --action_set=full. By default, it starts the base scenario and the left player is controlled by the keyboard. Different types of players are supported (gamepad, external bots, agents...). For possible options run python3 -m gfootball.play_game -helpfull.

For gamepad：python3 -m gfootball.play_game --players=gamepad

so what is the param for external bots,agents for --players=XXX?

Thank you!

**Comment by vi3itor** [comment]
@yumianhuli2 Why do you keep asking the same questions? You have already had a similar one in #137. And you received an answer and link to look into the documentation. If you want to dig into something, check the documentation first, search among all GitHub issues, look into the code of how something is implemented, look into examples of usage. If you feel that something should be described or implemented better - do it. And then send a pull request. When you don't spend time reading the codebase and the documentation you simply show disgrace to the developers. Someone already described and implemented it. I know that it sounds rude, but I think it is very rude to waste other's time too. Instead of replying to your questions, the developers could implement new features. Please, reconsider your other open issues (#174 #172) too.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Why do you keep asking the same questions? You have already had a similar one in #137. And you received an answer and link to look into the documentation. If you want to dig into something, check the documentation first, search among all GitHub issues, look into the code of how something is implemented, look into examples of usage. If you feel that something should be described or implemented better - do it. And then send a pull request. When you don't spend time reading the codebase and the documentation you simply show disgrace to the developers. Someone already described and implemented it. I know that it sounds rude, but I think it is very rude to waste other's time too. Instead of replying to your questions, the developers could implement new features. Please, reconsider your other open issues (#174 #172) too.

I am sorry I forget this answer!

**Comment by andrewchou** [comment]
@vi3itor i think that's normally a reasonable thing to say, but i think there's a higher standard for documentation as soon as you announce a competition. I love this project idea, but the documentation is not at the "announce a competition" level yet. But anyway, feel pride that others want to participate in what you've made!

**Comment by vi3itor** [comment]
@andrewchou I have no affiliation with Google. I just love the idea of the project too, that's why I decided to make some contributions in my free time. 

> but i think there's a higher standard for documentation as soon as you announce a competition. I love this project idea, but the documentation is not at the "announce a competition" level yet.

I have some connections with "AI in games" community, and I witnessed many game AI competitions that have less detailed documentation and less readable code. 

Again, I'm not a developer of the project, but let's imagine you are. What would you personally suggest to someone, who asks you questions, that are clearly defined in the documentation, and you already pointed out to them where to find the answer? On top of that, should you explain in your documentation about how to remove different versions of Tensorflow if someone accidentally installed both CPU and GPU version? Or what to do when someone messed up with Python installations? Would you be happy to see a dozen issues from someone who doesn't try reading documentation and code or googling error messages first?

I wouldn't be happy at all. So I wrote that message. Yes, it was rude and I should've put it differently. My main point was: I'd like to see developers improving the project and not spending time on issues like that. I hope we all agree, that it takes resources to provide support.
