### ISSUE TITLE
Py Install Error - Linux

### ISSUE THREAD

**Issue by Zaakir-Kamar** [google-research/football#179]
When "sudo -H pip install" command is given, when installing from source on a Linux machine, it raises an error
---
Processing /home/user/test/football
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Wevl40-build/setup.py", line 82, in <module>
        ext_modules=[CMakeExtension('brainball_cpp_engine')],
      File "/tmp/pip-Wevl40-build/setup.py", line 27, in __init__
        super().__init__(name, sources=[])
    TypeError: super() takes at least 1 argument (0 given)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Wevl40-build/

**Comment by vi3itor** [comment]
Why do you need to use `sudo`? Make sure you're using `pip3` and not `pip` from Python 2. 
A better way is to create a virtual environment as described in Readme: 
`python3 -m venv football-env`
Then activate it:
`source football-env/bin/activate`
And upgrade pip3 and setuptools: 
`pip3 install --upgrade pip setuptools wheel`
And run installation: 
`pip3 install .`

I recommend closing the issue because it is related to your system set up (same as #178) and not a football project.

**Comment by qstanczyk** [comment]
Alternatively you can try Docker setup which support rendering now:
https://github.com/google-research/football/blob/master/gfootball/doc/docker.md

Please reopen if you need further assistance.

**Comment by Zaakir-Kamar** [comment]
Ok. Thank you
