### ISSUE TITLE
is there an option for multiprocessing the environment?

### ISSUE THREAD

**Issue by Ujwal2910** [google-research/football#180]

**Comment by qstanczyk** [comment]
Yes, look at the example in PPO learner for example:
https://github.com/google-research/football/blob/master/gfootball/examples/run_ppo2.py#L47

Basically you can run multiple instances in a single process (but beware of performance limitations due to Python interpreter lock and the fact that only one environment instance can do rendering in this setup), or multi-process.

**Comment by qstanczyk** [comment]
Please reopen if you have follow-up questions.
