### ISSUE TITLE
No module named 'gfootball.eval_server'

### ISSUE THREAD

**Issue by AltmanD** [google-research/football#183]
When I follow the steps below​:

sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev \
libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev \
libdirectfb-dev libst-dev mesa-utils xvfb x11vnc libsdl-sge-dev python3-pip

pip install gfootball

pip3 install grpcio google-cloud-storage

​The following problems occurred:

~$python -c "import gfootball.eval_server"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gfootball.eval_server'

But "import gfootball" is good.

What's wrong with my steps?
thanks a lot!

**Comment by vi3itor** [comment]
Most likely, the reason is that you're mixing `python2` and `python3`. Many systems still use `python2` when you type `python` in the Terminal. The same goes for `pip` and `pip3`. So the correct way is `pip3 install gfootball` instead of `pip install gfootball`. 
And then you can run `python3 -c "import gfootball.eval_server"` without errors. 

I'll send a pull request to correct the Readme.
