### ISSUE TITLE
[Arch Linux / Manjaro] Unable to find the requested Boost libraries [boost_signals]

### ISSUE THREAD

**Issue by jmribeiro** [google-research/football#21]
When running pip install .[tf_cpu] --process-dependency-links, I'm getting the following error:

CMake Error at /usr/share/cmake-3.14/Modules/FindBoost.cmake:2165 (message):```

    Unable to find the requested Boost libraries.
  
    Boost version: 1.69.0
  
    Boost include path: /usr/include
  
    Could not find the following Boost libraries:
  
            boost_signals
  
    Some (but not all) of the required Boost libraries were found.  You may
    need to install these additional Boost libraries.  Alternatively, set
    BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
    to the location of Boost.

```

**Comment by cyfra** [comment]
Which operating system / version are you running on ?

Did you run the first step from README.md:

sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev libdirectfb-dev libst-dev mesa-utils xvfb x11vnc libsqlite3-dev glee-dev libsdl-sge-dev python3-pip

**Comment by jmribeiro** [comment]
Manjaro Linux, installed every lib of those through aur.

**Comment by cyfra** [comment]
CMake is looking for boost/signals.hpp (which seems to be missing).

Unfortunately I don't use ArchLinux/Manjaro - so I'm not sure which of the aur packages is including that module.

**Comment by liuhuo** [comment]
boost drops original Signals(v1) lib since 1.69.0, so you need a older version of boost(1.68.0 is fine in this case). My suggestion is to pull the 1.68.0 version of boost through abs (Arch Build System) and build it locally(but DO NOT install it system wide), then modify the CMakeLists.txt to using the newly built local 1.68.0 version, just add the followling line before find_pacakge(boost blah-blah-blah) to let cmake find the desired version of boost:
set(Boost_NO_SYSTEM_PATHS ON)
set(BOOST_ROOT "your_newly_built_boost_root_dir")
set(BOOST_INCLUDEDIR "your_newly_built_boost_include_dir")
set(BOOST_LIBRARYDIR "your_newly_built_boost_so_lib_dir, note that in archlinux the dynamic libs are in some different dir called boost-lib, boost dir only contains static libs")

btw, in order to run this project in archlinux, you need to  check the pinned "process-dependency-links flag not found" issue (since the pip version in archlinux is most likely to be greater than 19.0);
and also install glee and sge-git from aur, then modify FindSGE.cmake accordingly

**Comment by qstanczyk** [comment]
The next environment release moves codebase to signals2 implementation, so this issue will be resolved then. Stay tuned.

**Comment by qstanczyk** [comment]
We just pushed a new release, environment uses signals2 now.
