### ISSUE TITLE
[Question] How to get the location ([x, y] position) of the ball and players in the rendered frame (not in minimap)?

### ISSUE THREAD

**Issue by saikat927** [google-research/football#213]
I want to get the location ([x, y] position) of the ball and the players with respect to the rendered frame. The environment provides API to get the location of the ball and players in the whole soccer field called mnimap, as stated [here](https://github.com/google-research/football/blob/master/gfootball/doc/observation.md). But when a frame is rendered for display, only a small part of the field is displayed in a dynamic perspective, and I want the player-ball location in the rendered frame. How can I get that, any idea?
Is there any function/API available to translate a minimap coordinate to the frame coordinate?

**Comment by qstanczyk** [comment]
There is no exposed API for getting this information. You could hook up into the rendering pipeline to get that, but would require changing C++ implementation of the environment. May I ask why you want to get this information? Maybe there is a different, simpler way of solving the problem.

**Comment by saikat927** [comment]
One can utilize the information regarding the location of the ball and players in a frame in various ways. Let's say a computer vision researcher wants to process the raw frame and produce some results. The result may include player and ball localization, tracking, event detection, etc. For all of these cases, the location of the ball and players can be used for validation purposes. There may be some other possibilities.

**Comment by qstanczyk** [comment]
I see, makes sense. For such use case I guess the most generic solution would be to extend observations with information about camera, so that players' positions within the screen can be computed from camera position/direction and player's position. There was similar discussion in the past, so maybe you could sync up with the authors of that thread and see if they implemented something for this. Would be great to get a Pull request with such feature.
