### ISSUE TITLE
Bug - Position of players incorrect in some academy scenarios

### ISSUE THREAD

**Issue by tomberthon** [google-research/football#230]
When trying to use the following scenarios the right team players are positioned as if they are the left team:

- academy_empty_goal
- academy_empty_goal_close
- academy_run_to_score
- academy_run_to_score_with_keeper - In this scenario the keeper is in the right position, but the other players are not

The x position of the right team players should be negative.

**Comment by sakhan007** [comment]
Perhaps this is the purpose of these academies to test how your agent reacts to such situations!

**Comment by kkurach** [comment]
It's not a bug, the players are added there on purpose (it's an implementation detail of those scenarios).
In empty goal, the opponents are far away which simulates "no opponents" (the game engine doesn't allow 0 opponents)

In "run_to_score", the opponents are placed so that if you don't learn to run, they will catch you and take the ball.

**Comment by tomberthon** [comment]
Thanks - Makes sense if there has to be a player on the pitch for both sides.
