### ISSUE TITLE
Update setup.py to allow pygame>=2

### ISSUE THREAD

**Issue by maincarry** [google-research/football#251]
The current installation instruction for macOS does not work because brew will instead Python 3.9 and its corresponding boost library. However, Python 3.9 does not support the required pygame==1.9.6 and thus the instruction would fail. 

I did a fresh install of gfootball==2.6 on my Mac. I have Python 3.9.1 (installed by brew install python3). I installed pygame 2.0.1 and Pillow 8.1.0. It seems to me that everything works fine. I can play the game using `python3 -m gfootball.play_game --action_set=full`.

Could anyone using Python 3.9 share their experience? If everything works well, let's relax the pygame version requirement so people can install the game more easily using pip.

**Comment by vi3itor** [comment]
I will check it out on my Mac tomorrow. Pygame 2 was in beta for a long time. But since it is [finally released](https://github.com/pygame/pygame/releases/tag/2.0.0) and looks like it is backward compatible, it might be a good idea to upgrade the dependency.

**Comment by vi3itor** [comment]
Yes, it works on my Mac running Big Sur 11.1 with the latest versions of `python3`, `boost` and `boost-python3` installed via `brew`. In fact, it even runs faster. But there are some additional steps required for successful compilation since `gym` depends on `Pillow==7.2.0`, which in turn [doesn't support](https://pillow.readthedocs.io/en/stable/installation.html#python-support) `Python 3.9`. Until `gym` supports `Pillow==8.*` [the workaround](https://github.com/python-pillow/Pillow/issues/4816#issuecomment-735252148) is to install `zlib` and add its headers to the path:
```bash
brew install zlib
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"
export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
``` 
I will test `pygame 2` on my Ubuntu machine before sending the PR, but I remember that even beta versions worked without any problems.

**Comment by DwightFoster** [comment]
@vi3itor Did you ever figure out a way for ubuntu, because I am stuck on this problem right now. I cannot seem to get around using pygame 1.9.6 but I do not have any older versions of python installed so I am stuck.

**Comment by vi3itor** [comment]
Hi @DwightFoster! Yes, I was able to install and run it with Python 3.9 on Ubuntu. Because OpenAI's `gym` still doesn't support `Pillow 8`, we have to install the required packages manually and then install `gym` and football itself without dependencies. (For those who have Ubuntu 18.04, you need to install `Python 3.9` manually). The list of the commands should be as follows:
```bash
# create a virtual environment first and activate it
python -m venv football-env
source football-env/bin/activate
# upgrade pip
pip install --upgrade pip
pip install wheel absl-py
pip install Pillow cloudpickle pyglet numpy scipy pygame opencv-python
# now we are ready to install gym without any dependencies to avoid downgrading Pillow
pip install --no-deps gym
# finally, we can run the installation for the repository (again, without dependencies)
pip install --no-deps . 
``` 
Let me know if you run into any trouble.

**Comment by superxingzheng** [comment]
Trying with Ubuntu 20.04's default Python 3.8.5. Installation passed but keyboard notworking.

**Comment by qstanczyk** [comment]
In 2.9 release I have changed the dependence to pygame>=1.9.6.

**Comment by qstanczyk** [comment]
I have also updated [Docker example](https://github.com/google-research/football/blob/master/gfootball/doc/docker.md#tensorflow-without-gpu-training-support-version) to use Ubuntu 20.04 and keyboard works fine there. Please give it a try.
