### ISSUE TITLE
Is it possible to render offscreen on server for gfootball.play_game ?

### ISSUE THREAD

**Issue by qiyuangong** [google-research/football#27]
I think that will be pretty interesting. If we can launch this program in a powerful server, and redirect its video to client. :)

**Comment by cyfra** [comment]
Yes, you can. Using standard linux tools: Xvfb + DISPLAY + x11vnc (for example).

// In the commands below, I'm using ":1" as the display id - you can pick any number.

// This creates a "fake" framebuffer, where data will be rendered.
Xvfb :1 -screen 0 800x600x24 &

// This is "hosting" your framebuffer as VNC server (that you can use your client to connect to).
// WARNING: there are some additional options to set here, to have a secure connection.
x11vnc -display :1 -localhost &

// And then start the game - setting the DISPLAY variable, so that game is sending video to the right location.
env DISPLAY=:1.0 python3 -m gfootball.play_game

**Comment by qiyuangong** [comment]
> Yes, you can. Using standard linux tools: Xvfb + DISPLAY + x11vnc (for example).
> 
> // In the commands below, I'm using ":1" as the display id - you can pick any number.
> 
> // This creates a "fake" framebuffer, where data will be rendered.
> Xvfb :1 -screen 0 800x600x24 &
> 
> // This is "hosting" your framebuffer as VNC server (that you can use your client to connect to).
> // WARNING: there are some additional options to set here, to have a secure connection.
> x11vnc -display :1 -localhost &
> 
> // And then start the game - setting the DISPLAY variable, so that game is sending video to the right location.
> env DISPLAY=:1.0 python3 -m gfootball.play_game

Wow, thanks. Look nice. 

I will try it in our local environment. :)

**Comment by qiyuangong** [comment]
It works. 👍 
But the video has a bit slower than local rendering. I guess it is related to network and VNC resolution.

Thank you very much, @cyfra .

Issue closed.

**Comment by IouJenLiu** [comment]
Hi @cyfra 

With xvfb, it seems that the rendering is performed on CPU. Could we enable GPU-based rendering on remote server? Thanks!
