### ISSUE TITLE
No module named 'gfootball-engine'

### ISSUE THREAD

**Issue by minhoooo1** [google-research/football#281]
![微信图片_20210717094155](https://user-images.githubusercontent.com/61350752/126022142-0b4efd89-423a-4c0d-884a-616af2c56f15.png)
How can I solve it? please

**Comment by vi3itor** [comment]
You haven't installed `gfootball` properly. Please follow the instructions in [README.md](https://github.com/google-research/football#2a-from-pypi-package). You can also try `Docker`.

Your log suggests that you're using `anaconda`, so you should install `gfootball` in the environment. When posting an error, please use `code block ` instead of a screenshot.

**Comment by minhoooo1** [comment]
Thank you very much!



发自我的iPhone


------------------ Original ------------------
From: Victor Khaustov ***@***.***&gt;
Date: Tue,Jul 20,2021 7:35 PM
To: google-research/football ***@***.***&gt;
Cc: minhoooo1 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [google-research/football] No module named 'gfootball-engine' (#281)





 
You haven't installed gfootball properly. Please follow the instructions in README.md. You can also try Docker.
 
Your log suggests that you're using anaconda, so you should install gfootball in the environment. When posting an error, please use code block  instead of a screenshot.
