### ISSUE TITLE
libGL error: No matching fbConfigs or visuals found

### ISSUE THREAD

**Issue by daming-lu** [google-research/football#291]
I tried both `with gpu` and `without gpu` but got the same error like below:

```bash
root@fe4efb18c9d7:/gfootball# python3 -m gfootball.play_game --action_set=full
pygame 2.0.1 (SDL 2.0.14, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  96
  Current serial number in output stream:  97

```

My GPU works fine. Please see the screenshot

![Screenshot from 2021-09-03 13-36-15](https://user-images.githubusercontent.com/5635322/132062906-a6c2754e-a587-43d0-bf2e-a80cc08ebeba.png)

**Comment by vi3itor** [comment]
Hi @daming-lu, I have an Ubuntu 18.04  setup with NVIDIA TITAN Xp and I can confirm a similar error when running the game in rendering mode via Docker or even a simple `glxgears` program. It used to work fine, so it is probably connected with NVidia driver updates. I didn't have enough time to test and find a solution, but it looks like [there](https://github.com/jessfraz/dockerfiles/issues/253) [are](https://unix.stackexchange.com/questions/589236/libgl-error-no-matching-fbconfigs-or-visuals-found-glxgears-error-docker-cu) [plenty](https://stackoverflow.com/questions/46586013/glxgears-not-working-inside-of-docker) [of](https://stackoverflow.com/questions/44166269/libgl-error-failed-to-load-driver-swrast-in-docker-container) [complaints](https://answers.ros.org/question/322029/nvidia-driver-problem-in-ubuntu-1804-host-with-a-ros-kinetic-desktop-full-docker/). 

Could you please share your setup (OS, GPU card), and the steps you've already tried to resolve the issue? In the meantime, until the fix is found and the docs are updated, I suggest running the game in the rendering mode without Docker by following [the instructions](https://github.com/google-research/football#linux).

**Comment by Uwonsang** [comment]
me too, I got the same error on docker.
