### ISSUE TITLE
Cannot find boost python

### ISSUE THREAD

**Issue by zixianma** [google-research/football#310]
Hi, 

When I tried to run cmake for compiling the game engine, I got the boost python not found error shown below:

 Using Python: 3.5.2
Boost  found.
Found Boost components:
   python3-py35
python3-py35 not found. Trying other names.
Boost  found.
Found Boost components:
   python-py35
python-py35 not found. Trying other names.
Boost  found.
Found Boost components:
   python35
CMake Error at CMakeLists.txt:71 (message):
  Python boost not found

I do have /usr/lib/x86_64-linux-gnu/libboost_python-py35.so though. What might be the reason that find_package() didn't find it? What are some solutions?

**Comment by vi3itor** [comment]
Hi!

Based on your system version of Python, it looks like you're using Ubuntu 16.04. Do you have the opportunity to upgrade the operating system to at least 18.04? Upgrade to Ubuntu 20.04 would be much, much better. 

On Ubuntu 16.04, the system version of Python is 3.5, which reached the end of life on 13 Sep 2020. Python 3.6 (the default version on Ubuntu 18.04) is also no longer supported since 23 Dec 2021. The version of Boost Python that you get with `apt-get install` is compiled against the system version, so on Ubuntu 16.04, you're stuck with libboost_python-py35.so.
Also, pip dropped support for Python 3.5 since version `22.0`.

But your log clearly shows that CMake finds Boost Python component, but it continues the search anyway. That's interesting, but there are plenty of reasons why you get an error. 
What version of CMake do you use? (run `cmake --version`) If it is the default one for Ubuntu 16.04, it is probably `3.5.1`.

Can you comment out line 113 and see if it solves the problem:
```cmake
if(NOT DEFINED BOOST_PYTHON_VERSION)
  # message(FATAL_ERROR "Boost Python not found")
endif()
```

You can also try [updating `cmake`](https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line), but again, updating the Ubuntu is much better. I couldn't even build a Docker image for Ubuntu 16.04 because `pip` doesn't support Python 3.5 anymore.

**Comment by zixianma** [comment]
Hi, I've upgraded my ubuntu system to 20.04 and reinstalled everything following the instructions. The environment works now! Thanks so much : )
