### ISSUE TITLE
Installing Packages into Spyder 3.9 on Mac

### ISSUE THREAD

**Issue by maximfedorchak1** [google-research/football#322]
I have a problem with installing any packages not part of the original Spyder Python 3.9 library. I have already tried to install a couple of packages and none have worked. I have tried all sorts of different methods and commands to install these packages including pip, brew, and conda. I tried to install pyperclip and pygame and no websites or videos are getting through to my computer. Also, when I try to install pygame, I always get the same error in my terminal, 'ERROR: Failed building wheel for pygame'
Every time I try to import these new packages in my console, I get the ModuleNotFoundError. At this point, I'm completely lost.

**Comment by vi3itor** [comment]
Hi @maximfedorchak1,

It's hard to help you without seeing the installation logs and knowing your hardware (Intel or Apple Silicon). It's also difficult to find the cause of the problem if there were some installation conflicts or if Spyder blocks your attempts to try other python installations. I'm not familiar with Spyder, so I can't tell how to resolve issues with it, but I can confirm that with a fresh install you can run Google Research Football on both Intel and Apple Silicon Macs, and you can use either `brew` version of python (recommended) or the one from `conda`. 

If you struggle to install any modules because of Spyder, I would suggest to completely remove it and have a fresh start. Follow the [detailed guide](https://github.com/google-research/football/blob/master/gfootball/doc/compile_engine.md#macos-both-intel-processors-and-apple-silicon) on how to install gfootball on macOS, but before running the game install `six` module (`python3 -m pip install six`).
