### ISSUE TITLE
Docker-gpu image is based on python3.5

### ISSUE THREAD

**Issue by PBarde** [google-research/football#87]
Hi, 
could you provide a docker gpu image compatible with python 3.6 ? The current image is on python 3.5 and is not compatible with f strings for example. 
Also could you provide the command line to directly build a singularity image ? 
Thank you

**Comment by PBarde** [comment]
Hi, 
It does not run as is, there is some issue with tensorflow-probability it seems

**Comment by AntonRaichuk** [comment]
@PBarde: as per https://hub.docker.com/r/tensorflow/tensorflow/
instead of running
docker build --build-arg DOCKER_BASE=tensorflow/tensorflow:1.12.0-gpu-py3 --build-arg DEVICE=gpu . -t gfootball
if you run
docker build --build-arg DOCKER_BASE=tensorflow/tensorflow:1.14.0-gpu-py3 --build-arg DEVICE=gpu . -t gfootball

(the only diff is 1.12 -> 1.14), you'll get an image with python 3.6.
